#pragma config(Motor,  port2,           leftDriveMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           rightDriveMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftShooterMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           rightShooterMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           intakeMotor,   tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------*\
|*                                - Clawbot DOUBLE Joystick Control -                           *|
|*                                      ROBOTC on VEX 2.0 Cortex                                *|
|*                                                                                              *|
|*  This program uses TWO joystickS, BOTH right AND left to drive the robot (TANK DRIVE).       *|
|*  Use notes below to reconfigure which joystick is used.                                      *|
|*  The joystick buttons are used to raise and lower the arm.                                   *|
|*  The joystick buttons are used to open and close the claw.                                   *|
|*                                                                                              *|
|*                                        ROBOT CONFIGURATION                                   *|
|*  NOTES:                                                                                      *|
|*      1)  Ch2 is the Y axis for the RIGHT joystick.                                           *|
|*      2)  Ch3 is the Y axis for the LEFT joystick.                                            *|
|*      3)  Button 5U and 5L are on the front left side of the joystick.                        *|
|*      4)  Button 6U and 6L are on the front right side of the joystick.                       *|
|*                                                                                              *|
|*    MOTORS & SENSORS:                                                                         *|
|*    [I/O Port]        [Name]          [Type]                               [Description]      *|
|*    Motor - Port 2   leftMotor     PWM Motor                             Left drive motor     *|
|*    Motor - Port 3   rightMotor    PWM Motor                             Right drive motor    *|
|*    Motor - Port 5   clawMotor     servo                                 Claw control         *|
|*    Motor - Port 6   armMotor      PWM Motor                             Arm motor            *|
\*----------------------------------------------------------------------------------------------*/
/*************************************************************************************************

This is literally the the Demobot code but I adapted it for our Occra bot. So ghetto.

~Chris

**************************************************************************************************/
// joystick button functions
#define LEFT_TANK_THROTTLE         vexRT[Ch2]
#define RIGHT_TANK_THROTTLE				 vexRT[Ch3]
//#define ARCADE_STEER							 vexRT[Ch1]
//#define ARCADE_THROTTLE					   vexRT[Ch3]
#define FULL_SPEED_SHOOTER				 vexRT[Btn8RXmtr2]
#define ARCADE_MODE_ON						 vexRT[Btn8R]
#define TANK_MODE_ON						   vexRT[Btn8L]
#define HALF_SPEED_SHOOTER				 vexRT[Ch2Xmtr2]
//#define BELT_INTAKE								 vexRT[Ch3Xmtr2]
#define INTAKE_MOTOR							 vexRT[Ch3Xmtr2]


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++
task main ()
{
	int   counter10ms = 0;                            // initialize the timer
	bool arcadeMode = false;

	while( true )                                   // infinite loop
	{/*
		if(INTAKE_THE_BALLS)			//intake activates (mmm... rubber is my favorite food.)
		{
		motor[intakeMotor] = 64;
		motor[beltMotor1]  = 64;
		motor[beltMotor2]  = 64;
		};
		*/




		if(TANK_MODE_ON > 0.5)
		{
			arcadeMode = false;
		}

		if(ARCADE_MODE_ON > 0.5)
		{
			arcadeMode = true;
		}




		//tank drive




		//left drive factoring
		float leftFloatingThrottle;
		leftFloatingThrottle = LEFT_TANK_THROTTLE;

		leftFloatingThrottle /= 127; //divide by 127
		leftFloatingThrottle = leftFloatingThrottle * leftFloatingThrottle * leftFloatingThrottle; //cube
		leftFloatingThrottle = leftFloatingThrottle * 127; //multiply it back to scale

		motor[leftDriveMotor] = leftFloatingThrottle * -0.75;

		//right drive factoring
		float rightFloatingThrottle = RIGHT_TANK_THROTTLE;

		rightFloatingThrottle /= 127; //div by 127
		rightFloatingThrottle = rightFloatingThrottle * rightFloatingThrottle * rightFloatingThrottle; //cube
		rightFloatingThrottle = rightFloatingThrottle * 127; // multiply back to scale

		motor[rightDriveMotor] = rightFloatingThrottle * -0.75;



		//motor[leftDriveMotor] = ARCADE_THROTTLE + ARCADE_STEER;
		//motor[rightDriveMotor] = ARCADE_THROTTLE - ARCADE_STEER;


		//shooter motor
		if(FULL_SPEED_SHOOTER)
		{
			motor[leftShooterMotor] = 64; //full speed for goal
			motor[rightShooterMotor] = 64;
		}
		//Shooter motor at half speed for fence
		if(HALF_SPEED_SHOOTER)
		{
			motor[leftShooterMotor] = 32;
			motor[rightShooterMotor] = 32;
		}

		/*if(BELT_INTAKE)
		{
			motor[beltMotor1] = 64;
			motor[beltMotor2] = 64;
		}
		*/
		motor[intakeMotor] = INTAKE_MOTOR;



		//10ms between executions of the infinite loop
		wait1Msec(10);
		counter10ms += 1;                           // increment the counter of 10ms loops
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
